### ISSUE TITLE
[BUG] ECS Initializer "Features" incorrect display

### ISSUE THREAD

**Issue by hizzd** [chromealex/ecs#10]
**Describe the bug**
ECS Initializer "Features" incorrect display

**Screenshots**
<img width="400" alt="image" src="https://user-images.githubusercontent.com/39532556/174549674-0174cfb2-ad9a-46f4-bd42-b9bd7eef652e.png">
<img width="408" alt="image" src="https://user-images.githubusercontent.com/39532556/174549715-8ab51f3b-ae61-4308-b303-678a5492dd55.png">
<img width="412" alt="image" src="https://user-images.githubusercontent.com/39532556/174549760-b972e373-5842-4625-9f84-0e34544e5167.png">
<img width="403" alt="image" src="https://user-images.githubusercontent.com/39532556/174549977-d258db71-8394-43c9-b56d-d315df7de5d4.png">

**Unity (please complete the following information):**
 - Version: 2021.3.4f1c1 apple silicon
`It seems that this project recommend unity2020, but since unity support for apple silicon only started from 2021 version, I had to use unity 2021`

**Additional context**

ecs-submodule: 2.4.100

MacBook Pro 16' 2021
macOS 13.0

**Comment by hizzd** [comment]
It seems that only the first element incorrect display.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/39532556/174556007-370b894a-90af-42ec-b02e-e372fb1d4b1d.png">

**Comment by chromealex** [comment]
Tested in
2021.3.0f1
2020.3.26f1
Works as expected ;(

**Comment by hizzd** [comment]
i open Pong Out example in 2021.3.0f1, it is work.
but open in 2021.3.4f1, not work.

2021.3.0f1:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/39532556/174650998-e2a079a6-29b7-4332-bc48-6d285d1a0557.png">

2021.3.4f1:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/39532556/174651377-e1af1a3c-09b7-4865-bdd7-075b043318d4.png">

**Comment by chromealex** [comment]
Ok, I will check it in 2021.3.4f1. Is it the last available unity version in 2021 branch?

**Comment by hizzd** [comment]
yes

**Comment by chromealex** [comment]
Seems like it's a bug in Unity property drawers. May be you can use previous version of unity and when the patch release will be available - you will be ready to use 2021.3.4f1. Agree?

**Comment by hizzd** [comment]
ok, thanks you :)
