### ISSUE TITLE
Assembly Reload Time

### ISSUE THREAD

**Issue by echeg** [chromealex/ecs#4]
The latest version of the framework has a huge Assembly Reload Time 

Test on Unity 2019.4.26f1 2020.2.xx 2020.1.xx
Use https://github.com/chromealex/ecs.example 

Profiling tool https://github.com/Unity-Technologies/com.unity.editoriterationprofiler

By default Reload time (fast)  
![image](https://user-images.githubusercontent.com/793087/117478032-59eb0980-af67-11eb-81f2-c69906988c53.png)

After update to last version (slow)  
![image](https://user-images.githubusercontent.com/793087/117478175-7c7d2280-af67-11eb-906a-0186d768d187.png)

In a real case, without debugging. Changing 1 line of code in one case takes 4s, in another 12s.  
If you remove Burst and Collections, the time drops from 12s to 8s  

Is there anything you can do about this? For fast iteration, an initial compilation time of 12s is very annoying... 
And one more question. Is it possible to develop without a Unity? Is it possible to build game logic and framework code (without unity) to DLL?

**Comment by chromealex** [comment]
Hi!

Sorry about that, I’ll take a look into reload components generator. Hope
it helps:
Turn off auto generate by selecting ME.ECS/Generator/struct components/auto
generate
Btw I’ll check this method to get it works faster.
About unity: you can try to turn off all UNITY defines (look into csc.rsp),
but may be there are some problems with some dependencies, not tested yet.

**Comment by echeg** [comment]
> Turn off auto generate by selecting ME.ECS/Generator/struct components/auto generate

Yes thanks it helps.
"Struct Components
To be able to use struct components in jobs, you need some sort of magic to register all your struct components while project initialization."
those. if i don't use Jobs will everything be ok? )

**Comment by chromealex** [comment]
Hope all is ok
