### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by logixworx** [chromealex/ecs#6]
Unable to install this project - instructions unclear / outdated. 

Which version of unity is required?  Project seems to require outdated unity modules.

**Comment by chromealex** [comment]
Hi
I have tested with Unity 2020 and 2021.
About dependencies. You can use latest versions of all listed packages.
If you have any trouble with set up - let me know.

**Comment by valanchik** [comment]
> Hi I have tested with Unity 2020 and 2021. About dependencies. You can use latest versions of all listed packages. If you have any trouble with set up - let me know.

![image](https://user-images.githubusercontent.com/4766751/140670163-fe10f8de-7496-4f5d-8070-60e60ffaa5a6.png)

**Comment by chromealex** [comment]
@valanchik I think this is because of beta version, why you not use stable one? Seems like you unity.ui package doesn’t work with unity beta version. It’s not a problem with dependencies, sorry.

**Comment by valanchik** [comment]
> @valanchik I think this is because of beta version, why you not use stable one? Seems like you unity.ui package doesn’t work with unity beta version. May be you can use submodule installation instead of UPM installation, it should help.

Я просто что-то новое тестирую на самых новых версиях unity. А если под apple silicon(m1) , так там вообще  альфа :).  
На 2019 всё работает.
Спасибо за ответ.
