### ISSUE TITLE
[BUG] error CS2001

### ISSUE THREAD

**Issue by valanchik** [chromealex/ecs#7]
![image](https://user-images.githubusercontent.com/4766751/140834631-fdc1c8be-d59c-465b-b680-69482a199bc1.png)

**Comment by chromealex** [comment]
Have you create csc.gen.rsp file in Assets folder?

**Comment by valanchik** [comment]
yes
![image](https://user-images.githubusercontent.com/4766751/140975542-98f26d60-040b-4493-b4df-c23904eb4177.png)

**Comment by chromealex** [comment]
Is file csc.gen.rsp empty? Seems like it has a break line:)

**Comment by chromealex** [comment]
https://github.com/chromealex/ecs/blob/master/Assets/csc.gen.rsp
You can use this one

**Comment by valanchik** [comment]
> Is file csc.gen.rsp empty? Seems like it has a break line:)

yes, the file was not empty. :) This is because I have a habit of creating an empty file as a new rtf document. Therefore, inside my file there was the following content "{\rtf1}"
I cleared the file and everything worked, thank you!
